#!/bin/bash
# =============================================================================
#  VastraX — FASHN VTON 1.5 GPU Setup Script
#  Run this ONCE on the Linux GPU machine (RTX 4090 / 5070 Ti or similar).
#  Sets up the FASHN model, Python venv, and backend .env automatically.
#
#  Usage:
#    chmod +x gpu-setup/setup_fashn.sh
#    ./gpu-setup/setup_fashn.sh
# =============================================================================

set -e

INSTALL_BASE="$HOME/fashn-tryon"
VENV_DIR="$INSTALL_BASE/venv"
FASHN_DIR="$INSTALL_BASE/fashn-vton-1.5"
BACKEND_DIR="$(cd "$(dirname "$0")/../backend" && pwd)"

print_section() { echo ""; echo "──────────────────────────────────────────"; echo "  $1"; echo "──────────────────────────────────────────"; }

print_section "1/6  Checking prerequisites"

if ! command -v python3 &>/dev/null; then
  echo "ERROR: python3 not found. Install Python 3.10+ first."
  exit 1
fi

if ! command -v git &>/dev/null; then
  echo "ERROR: git not found. Run: sudo apt install git"
  exit 1
fi

if ! command -v nvcc &>/dev/null && ! command -v nvidia-smi &>/dev/null; then
  echo "WARNING: NVIDIA drivers / CUDA not detected. Make sure CUDA 12.x is installed."
fi

PYTHON_VER=$(python3 -c "import sys; print(f'{sys.version_info.major}.{sys.version_info.minor}')")
echo "Python version : $PYTHON_VER"
echo "Install target : $INSTALL_BASE"
echo "Backend dir    : $BACKEND_DIR"

# ── Step 2: Clone FASHN VTON 1.5 ──────────────────────────────────────────
print_section "2/6  Cloning FASHN VTON 1.5"

mkdir -p "$INSTALL_BASE"

if [ -d "$FASHN_DIR/.git" ]; then
  echo "FASHN repo already cloned, pulling latest..."
  git -C "$FASHN_DIR" pull
else
  echo "Cloning fashn-ai/fashn-vton-1.5 ..."
  git clone https://github.com/fashn-AI/fashn-vton-1.5.git "$FASHN_DIR"
fi

# ── Step 3: Python virtual environment ────────────────────────────────────
print_section "3/6  Creating Python venv"

if [ ! -d "$VENV_DIR" ]; then
  python3 -m venv "$VENV_DIR"
  echo "Virtual env created at $VENV_DIR"
else
  echo "Virtual env already exists, skipping."
fi

VENV_PYTHON="$VENV_DIR/bin/python"
VENV_PIP="$VENV_DIR/bin/pip"

# ── Step 4: Install PyTorch + FASHN deps ──────────────────────────────────
print_section "4/6  Installing PyTorch (CUDA 12.1) and FASHN dependencies"

"$VENV_PIP" install --upgrade pip

# PyTorch with CUDA 12.8 — required for RTX 5070 Ti (Blackwell / sm_120)
"$VENV_PIP" install torch torchvision --index-url https://download.pytorch.org/whl/cu128

# FASHN model dependencies
"$VENV_PIP" install \
  diffusers \
  transformers \
  accelerate \
  controlnet_aux \
  Pillow \
  numpy \
  opencv-python-headless \
  einops \
  omegaconf \
  safetensors \
  huggingface_hub

# Also install any requirements that ship with the repo
if [ -f "$FASHN_DIR/requirements.txt" ]; then
  "$VENV_PIP" install -r "$FASHN_DIR/requirements.txt"
fi

# ── Step 5: Download model weights ────────────────────────────────────────
print_section "5/6  Downloading FASHN VTON 1.5 weights"

WEIGHTS_DIR="$FASHN_DIR/weights"
mkdir -p "$WEIGHTS_DIR"
mkdir -p "$FASHN_DIR/results"

# Use the download script if it exists, otherwise use huggingface_hub
if [ -f "$FASHN_DIR/scripts/download_weights.py" ]; then
  "$VENV_PYTHON" "$FASHN_DIR/scripts/download_weights.py" --weights-dir "$WEIGHTS_DIR"
elif [ -f "$FASHN_DIR/download_weights.py" ]; then
  "$VENV_PYTHON" "$FASHN_DIR/download_weights.py" --weights-dir "$WEIGHTS_DIR"
else
  echo "Downloading weights via huggingface_hub..."
  "$VENV_PYTHON" - <<PYEOF
from huggingface_hub import snapshot_download
snapshot_download(
    repo_id="fashn-ai/fashn-vton-1.5",
    local_dir="$WEIGHTS_DIR",
    ignore_patterns=["*.md", ".gitattributes"]
)
print("Weights downloaded to $WEIGHTS_DIR")
PYEOF
fi

# ── Step 6: Write backend .env ─────────────────────────────────────────────
print_section "6/6  Writing backend/.env"

ENV_FILE="$BACKEND_DIR/.env"

cat > "$ENV_FILE" <<EOF
# Auto-generated by gpu-setup/setup_fashn.sh

PORT=8088
ALLOWED_ORIGINS=*
UPLOAD_DIR=user_uploads
RESULTS_DIR=results

FASHN_VENV=$VENV_PYTHON
FASHN_SCRIPT=$FASHN_DIR/examples/basic_inference.py
FASHN_WEIGHTS=$WEIGHTS_DIR
FASHN_OUTPUT=$FASHN_DIR/results/output_00.png
FASHN_RESULTS=$FASHN_DIR/results
EOF

echo "Written to $ENV_FILE"

# ── Install backend Python dependencies ───────────────────────────────────
print_section "Installing backend API dependencies"

if [ -f "$BACKEND_DIR/requirements.txt" ]; then
  pip3 install -r "$BACKEND_DIR/requirements.txt" --quiet
  echo "Backend requirements installed."
fi

# ── Done ──────────────────────────────────────────────────────────────────
echo ""
echo "=============================================="
echo "  FASHN VTON 1.5 setup complete!"
echo "=============================================="
echo ""
echo "  To start the full try-on stack, run:"
echo ""
echo "    python start-tryon.py"
echo ""
echo "  Or individually:"
echo "    Backend : cd backend && uvicorn app.main:app --host 0.0.0.0 --port 8088"
echo "    Tunnel  : python tunnel/tunnel.py"
echo ""
