"""Add 2factor SMS session ID

Revision ID: 737db7f8326f
Revises: ed045ba5fce3
Create Date: 2026-08-30 15:07:49.459199

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '737db7f8326f'
down_revision: Union[str, Sequence[str], None] = 'ed045ba5fce3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column('users', sa.Column('is_2fa_enabled', sa.Boolean(), nullable=False, server_default='0'))
    op.add_column('users', sa.Column('sms_session_id', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'sms_session_id')
    op.drop_column('users', 'is_2fa_enabled')

    # ### end Alembic commands ###
